# Site settings
title: CJ Blog
tagline: developer
email: caique_jh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Oi, eu sou um estudante da área das ciências exatas e nas horas vagas sou desenvolvedor/entusiasta
  Java, Ruby e Android.   
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caiquejhones.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Caique Jhones"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: CaiqueJhones
    twitter: caiquejhoones
    facebook: caique.jhoones
    gplus: u/0/106305622677689366046/about
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: cjoblog

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        none

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
