# Site settings
title: CJ Blog
tagline: developer
email: caique_jh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre programação, com tutoriais, cursos e bate papo sobre as novidades do mundo web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" #"http://caiquejhones.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Caique Jhones"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
author_desc: "Java Developer" # Author description
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: CaiqueJhones
    twitter: caiquejhoones
    facebook: caique.jhoones
    gplus: u/0/+CaiqueJhones/about
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: cjoblog

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-46646162-2
  google_webmaster_key: XBzdUzuchqfXicS59l_Cs-MLMG3XzS27gLMV5cXJLgM

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
